name: Lint

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
    
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          args: --timeout=5m
          working-directory: ./
